<?php
	require_once("Model/Select.class.php");
	require_once("Model/Insert.class.php");
	require_once("Model/Update.class.php");	
	require_once("Model/Delete.class.php");	
	require_once("config/database.php");
	require_once("Core/Model.class.php");
	require_once("Core/Controller.class.php");
	require_once("Core/Routeur.class.php");
	require_once("Core/Form.class.php");
	require_once("Core/Dispatcher.class.php");
?>
